# -*- coding: utf-8 -*-
"""Data_Cleaning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Egj-xYUNVOtVog4CfKcz52iBcaJhuRYr
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

df = pd.read_csv("/content/drive/MyDrive/datasets/diabetes_prediction_dataset.csv")
df.isnull().sum()
df.duplicated().sum()
df=df.drop_duplicates()
df.info()
for col in df.columns:
  print(col)
  unique_columns = df[col].unique()
  number = df[col].nunique()
  print(unique_columns)
  print(number)
  print("-"*100)


df_zeroes = df[df['diabetes'] == 0]
rows_to_remove = df_zeroes.shape[0] - 7000
rows_to_drop = df_zeroes.sample(n=rows_to_remove, random_state=42).index
df = df.drop(rows_to_drop)
print(df[df['diabetes'] == 0].shape[0])


df["age"]=pd.qcut(df["age"],5,labels=["child","young","adult","old","very old"])
df["bmi"]=pd.qcut(df["bmi"],5,labels=["underweight","normal","overweight","obese","extremely obese"])
df["HbA1c_level"] = pd.qcut(df["HbA1c_level"], 5, labels=["low", "normal", "high", "very high", "extreme high"])
df["blood_glucose_level"] = pd.qcut(df["blood_glucose_level"], 5, labels=["low", "normal", "high", "very high", "extreme high"])

# nominal encoding
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

label_encoder = LabelEncoder()
columns_label = ["gender"]
for col in columns_label:
  df[col] = label_encoder.fit_transform(df[col])
df

from sklearn.preprocessing import OrdinalEncoder

ordinal = OrdinalEncoder()

ordinal_columns=["age","hypertension"	,"heart_disease",	"smoking_history",	"bmi"	,"HbA1c_level",	"blood_glucose_level"]
for col in ordinal_columns:
  df[col] = ordinal.fit_transform(df[[col]])
df

x = df.drop("diabetes",axis=1)
y = df["diabetes"]

from sklearn.preprocessing import StandardScaler
scaled_columns = x.columns
scaler = StandardScaler()
x[scaled_columns] = scaler.fit_transform(x[scaled_columns])

x

