# -*- coding: utf-8 -*-
"""hugging face space

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JACKtMtgXZMd7kfHmVUO1afwPPXWwMkz
"""

import pandas as pd
import gradio as gr
import numpy as np
import joblib

# Load the trained model
model = joblib.load('/content/drive/MyDrive/models/DT_model_diabetes.sav')

# Prediction function
def predict_diabetes(gender, age, hypertension, heart_disease, smoking_history, bmi, HbA1c_level, blood_glucose_level):
    # Preprocess input data into the format required by the model
    gender = 0 if gender == "Male" else 1
    age_map = {"child": 0, "young": 1, "adult": 2, "old": 3, "very old": 4}
    age = age_map.get(age, 2)
    hypertension = 0 if hypertension == "No" else 1
    heart_disease = 0 if heart_disease == "No" else 1
    smoking_map = {"never": 0, "No Info": 1, "current": 2, "former": 3, "ever": 4}
    smoking_history = smoking_map.get(smoking_history, 1)
    bmi_map = {"underweight": 0, "normal": 1, "overweight": 2, "obese": 3, "very obese": 4}
    bmi = bmi_map.get(bmi, 1)
    HbA1c_map = {"low": 0, "normal": 1, "high": 2, "very high": 3}
    HbA1c_level = HbA1c_map.get(HbA1c_level, 1)
    glucose_map = {"low": 0, "normal": 1, "high": 2, "very high": 3}
    blood_glucose_level = glucose_map.get(blood_glucose_level, 1)

    # Create input array for the model
    input_data = np.array([[gender, age, hypertension, heart_disease, smoking_history, bmi, HbA1c_level, blood_glucose_level]])

    # Make prediction
    prediction = model.predict(input_data)
    result = "Positive" if int(prediction[0]) == 1 else "Negative"

    return result

# Define the Gradio interface
interface = gr.Interface(
    fn=predict_diabetes,
    inputs=[
        gr.Radio(["Male", "Female"], label="Gender"),
        gr.Radio(["child", "young", "adult", "old", "very old"], label="Age"),
        gr.Radio(["Yes", "No"], label="Hypertension"),
        gr.Radio(["Yes", "No"], label="Heart Disease"),
        gr.Radio(["never", "No Info", "current", "former", "ever"], label="Smoking History"),
        gr.Radio(["underweight", "normal", "overweight", "obese", "very obese"], label="BMI"),
        gr.Radio(["low", "normal", "high", "very high"], label="HbA1c Level"),
        gr.Radio(["low", "normal", "high", "very high"], label="Blood Glucose Level")
    ],
    outputs="text",
    title="Diabetes Prediction",
    description="Enter patient details to predict diabetes risk."
)
interface.launch(share=True)

!pip install gradio