# -*- coding: utf-8 -*-
"""model building and saving the model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-DN71rkYG4_TNK3quGapjNZ5qLZucYKF
"""

# model_building.py

import pandas as pd
import joblib
from sklearn.model_selection import train_test_split
from imblearn.combine import SMOTEENN
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load cleaned data
cleaned_data_path = '/content/drive/MyDrive/datasets/cleaned_diabetes_data.csv'  # Adjust the path if needed
df = pd.read_csv(cleaned_data_path)

# Prepare features and target variable
x = df.drop("diabetes", axis=1)  # Features
y = df["diabetes"]                # Target variable

# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Handle class imbalance using SMOTE-ENN
smote_enn = SMOTEENN(random_state=42)
x_train_r, y_train_r = smote_enn.fit_resample(x_train, y_train)

# Function to evaluate the Decision Tree model
def evaluate_DT(criterion, max_depth, x_train_r, x_test, y_train_r, y_test):
    dt = DecisionTreeClassifier(class_weight='balanced', criterion=criterion, max_depth=max_depth, random_state=42)
    dt.fit(x_train_r, y_train_r)

    # Save the trained model
    joblib.dump(dt, '/content/drive/MyDrive/models/DT_model_diabetes.sav')
    print(f"Best model saved to {'/content/drive/MyDrive/models/DT_model_diabetes.sav'}")

    # Make predictions on the test set
    y_predict = dt.predict(x_test)

    # Calculate evaluation metrics
    acc = accuracy_score(y_test, y_predict)
    report = classification_report(y_test, y_predict)
    cm = confusion_matrix(y_test, y_predict)

    return acc, report, cm

# Evaluate the Decision Tree model with specified parameters
acc_entropy, report_entropy, cm_entropy = evaluate_DT("entropy", 10, x_train_r, x_test, y_train_r, y_test)

# Print evaluation results
print("Accuracy:", acc_entropy)
print("Classification Report:\n", report_entropy)
print("Confusion Matrix:\n", cm_entropy)

from google.colab import drive
drive.mount('/content/drive')



